import type { Role } from '~/types'

// Определяем типы локально для серверного API
type PermissionLevel = 'full' | 'limited' | 'none'
type Permission = 
  | 'system.manage' | 'system.backup' | 'system.logs.view' | 'system.config'
  | 'users.create' | 'users.edit' | 'users.delete' | 'users.view' | 'users.roles.assign'
  | 'groups.create' | 'groups.edit' | 'groups.delete' | 'groups.view'
  | 'students.create' | 'students.edit' | 'students.delete' | 'students.assign_to_group'
  | 'course.create' | 'course.edit' | 'course.delete' | 'course.view' | 'course.assign_to_groups'
  | 'modules.create' | 'modules.edit' | 'modules.delete' | 'modules.view'
  | 'lab.create' | 'lab.edit' | 'lab.delete' | 'lab.view' | 'lab.execute' | 'lab.reset'
  | 'lab.assign_to_groups' | 'lab.template'
  | 'container.create' | 'container.start' | 'container.stop' | 'container.delete'
  | 'container.console' | 'container.logs' | 'container.resources.manage'
  | 'grades.create' | 'grades.edit' | 'grades.view' | 'grades.view_group' | 'grades.export'
  | 'results.download'
  | 'audit.view' | 'audit.view_groups' | 'audit.export'
  | 'monitoring.view' | 'monitoring.resources'
  | 'reports.generate' | 'reports.groups'
  | 'files.upload' | 'files.download' | 'files.delete' | 'files.share'

interface RoleData {
  id: string
  name: string
  description: string
  permissions: Record<Permission, PermissionLevel>
}

export default defineEventHandler(async (event) => {
  // В реальном приложении здесь будет запрос к базе данных
  // Пока возвращаем статические данные
  const roles: RoleData[] = [
    {
      id: 'root',
      name: 'root',
      description: 'Суперпользователь с полными системными правами',
      permissions: {
        'system.manage': 'full',
        'system.backup': 'full',
        'system.logs.view': 'full',
        'system.config': 'full',
        'users.create': 'full',
        'users.edit': 'full',
        'users.delete': 'full',
        'users.view': 'full',
        'users.roles.assign': 'full',
        'groups.create': 'full',
        'groups.edit': 'full',
        'groups.delete': 'full',
        'groups.view': 'full',
        'students.create': 'full',
        'students.edit': 'full',
        'students.delete': 'full',
        'students.assign_to_group': 'full',
        'course.create': 'full',
        'course.edit': 'full',
        'course.delete': 'full',
        'course.view': 'full',
        'course.assign_to_groups': 'full',
        'modules.create': 'full',
        'modules.edit': 'full',
        'modules.delete': 'full',
        'modules.view': 'full',
        'lab.create': 'full',
        'lab.edit': 'full',
        'lab.delete': 'full',
        'lab.view': 'full',
        'lab.execute': 'full',
        'lab.reset': 'full',
        'lab.assign_to_groups': 'full',
        'lab.template': 'full',
        'container.create': 'full',
        'container.start': 'full',
        'container.stop': 'full',
        'container.delete': 'full',
        'container.console': 'full',
        'container.logs': 'full',
        'container.resources.manage': 'full',
        'grades.create': 'full',
        'grades.edit': 'full',
        'grades.view': 'full',
        'grades.view_group': 'full',
        'grades.export': 'full',
        'results.download': 'full',
        'audit.view': 'full',
        'audit.view_groups': 'full',
        'audit.export': 'full',
        'monitoring.view': 'full',
        'monitoring.resources': 'full',
        'reports.generate': 'full',
        'reports.groups': 'full',
        'files.upload': 'full',
        'files.download': 'full',
        'files.delete': 'full',
        'files.share': 'full'
      }
    },
    {
      id: 'admin',
      name: 'admin',
      description: 'Системный администратор платформы',
      permissions: {
        'system.manage': 'full',
        'system.backup': 'full',
        'system.logs.view': 'full',
        'system.config': 'full',
        'users.create': 'full',
        'users.edit': 'full',
        'users.delete': 'full',
        'users.view': 'full',
        'users.roles.assign': 'full',
        'groups.create': 'full',
        'groups.edit': 'full',
        'groups.delete': 'full',
        'groups.view': 'full',
        'students.create': 'full',
        'students.edit': 'full',
        'students.delete': 'full',
        'students.assign_to_group': 'full',
        'course.create': 'full',
        'course.edit': 'full',
        'course.delete': 'full',
        'course.view': 'full',
        'course.assign_to_groups': 'full',
        'modules.create': 'full',
        'modules.edit': 'full',
        'modules.delete': 'full',
        'modules.view': 'full',
        'lab.create': 'full',
        'lab.edit': 'full',
        'lab.delete': 'full',
        'lab.view': 'full',
        'lab.execute': 'full',
        'lab.reset': 'full',
        'lab.assign_to_groups': 'full',
        'lab.template': 'full',
        'container.create': 'full',
        'container.start': 'full',
        'container.stop': 'full',
        'container.delete': 'full',
        'container.console': 'full',
        'container.logs': 'full',
        'container.resources.manage': 'full',
        'grades.create': 'full',
        'grades.edit': 'full',
        'grades.view': 'full',
        'grades.view_group': 'full',
        'grades.export': 'full',
        'results.download': 'full',
        'audit.view': 'full',
        'audit.view_groups': 'full',
        'audit.export': 'full',
        'monitoring.view': 'full',
        'monitoring.resources': 'full',
        'reports.generate': 'full',
        'reports.groups': 'full',
        'files.upload': 'full',
        'files.download': 'full',
        'files.delete': 'full',
        'files.share': 'full'
      }
    },
    {
      id: 'admin_edu',
      name: 'admin_edu',
      description: 'Администратор образовательного процесса',
      permissions: {
        'system.manage': 'none',
        'system.backup': 'none',
        'system.logs.view': 'none',
        'system.config': 'none',
        'users.create': 'none',
        'users.edit': 'none',
        'users.delete': 'none',
        'users.view': 'limited',
        'users.roles.assign': 'none',
        'groups.create': 'full',
        'groups.edit': 'full',
        'groups.delete': 'full',
        'groups.view': 'full',
        'students.create': 'full',
        'students.edit': 'full',
        'students.delete': 'full',
        'students.assign_to_group': 'full',
        'course.create': 'full',
        'course.edit': 'full',
        'course.delete': 'full',
        'course.view': 'full',
        'course.assign_to_groups': 'full',
        'modules.create': 'full',
        'modules.edit': 'full',
        'modules.delete': 'full',
        'modules.view': 'full',
        'lab.create': 'limited',
        'lab.edit': 'limited',
        'lab.delete': 'limited',
        'lab.view': 'full',
        'lab.execute': 'full',
        'lab.reset': 'full',
        'lab.assign_to_groups': 'full',
        'lab.template': 'limited',
        'container.create': 'none',
        'container.start': 'none',
        'container.stop': 'none',
        'container.delete': 'none',
        'container.console': 'none',
        'container.logs': 'none',
        'container.resources.manage': 'none',
        'grades.create': 'none',
        'grades.edit': 'none',
        'grades.view': 'full',
        'grades.view_group': 'full',
        'grades.export': 'full',
        'results.download': 'full',
        'audit.view': 'limited',
        'audit.view_groups': 'limited',
        'audit.export': 'none',
        'monitoring.view': 'limited',
        'monitoring.resources': 'none',
        'reports.generate': 'full',
        'reports.groups': 'full',
        'files.upload': 'full',
        'files.download': 'full',
        'files.delete': 'limited',
        'files.share': 'full'
      }
    },
    {
      id: 'admin_lab',
      name: 'admin_lab',
      description: 'Администратор лабораторных сред',
      permissions: {
        'system.manage': 'none',
        'system.backup': 'none',
        'system.logs.view': 'limited',
        'system.config': 'none',
        'users.create': 'none',
        'users.edit': 'none',
        'users.delete': 'none',
        'users.view': 'none',
        'users.roles.assign': 'none',
        'groups.create': 'none',
        'groups.edit': 'none',
        'groups.delete': 'none',
        'groups.view': 'limited',
        'students.create': 'none',
        'students.edit': 'none',
        'students.delete': 'none',
        'students.assign_to_group': 'none',
        'course.create': 'none',
        'course.edit': 'none',
        'course.delete': 'none',
        'course.view': 'limited',
        'course.assign_to_groups': 'none',
        'modules.create': 'none',
        'modules.edit': 'none',
        'modules.delete': 'none',
        'modules.view': 'limited',
        'lab.create': 'full',
        'lab.edit': 'full',
        'lab.delete': 'full',
        'lab.view': 'full',
        'lab.execute': 'full',
        'lab.reset': 'full',
        'lab.assign_to_groups': 'limited',
        'lab.template': 'full',
        'container.create': 'full',
        'container.start': 'full',
        'container.stop': 'full',
        'container.delete': 'full',
        'container.console': 'full',
        'container.logs': 'full',
        'container.resources.manage': 'full',
        'grades.create': 'none',
        'grades.edit': 'none',
        'grades.view': 'none',
        'grades.view_group': 'none',
        'grades.export': 'none',
        'results.download': 'limited',
        'audit.view': 'limited',
        'audit.view_groups': 'limited',
        'audit.export': 'none',
        'monitoring.view': 'full',
        'monitoring.resources': 'full',
        'reports.generate': 'limited',
        'reports.groups': 'none',
        'files.upload': 'full',
        'files.download': 'full',
        'files.delete': 'full',
        'files.share': 'limited'
      }
    },
    {
      id: 'admin_users_groups',
      name: 'admin_users_groups',
      description: 'Администратор пользователей и групп',
      permissions: {
        'system.manage': 'none',
        'system.backup': 'none',
        'system.logs.view': 'none',
        'system.config': 'none',
        'users.create': 'full',
        'users.edit': 'full',
        'users.delete': 'full',
        'users.view': 'full',
        'users.roles.assign': 'full',
        'groups.create': 'full',
        'groups.edit': 'full',
        'groups.delete': 'full',
        'groups.view': 'full',
        'students.create': 'full',
        'students.edit': 'full',
        'students.delete': 'full',
        'students.assign_to_group': 'full',
        'course.create': 'none',
        'course.edit': 'none',
        'course.delete': 'none',
        'course.view': 'none',
        'course.assign_to_groups': 'none',
        'modules.create': 'none',
        'modules.edit': 'none',
        'modules.delete': 'none',
        'modules.view': 'none',
        'lab.create': 'none',
        'lab.edit': 'none',
        'lab.delete': 'none',
        'lab.view': 'none',
        'lab.execute': 'none',
        'lab.reset': 'none',
        'lab.assign_to_groups': 'none',
        'lab.template': 'none',
        'container.create': 'none',
        'container.start': 'none',
        'container.stop': 'none',
        'container.delete': 'none',
        'container.console': 'none',
        'container.logs': 'none',
        'container.resources.manage': 'none',
        'grades.create': 'none',
        'grades.edit': 'none',
        'grades.view': 'none',
        'grades.view_group': 'none',
        'grades.export': 'none',
        'results.download': 'none',
        'audit.view': 'none',
        'audit.view_groups': 'none',
        'audit.export': 'none',
        'monitoring.view': 'none',
        'monitoring.resources': 'none',
        'reports.generate': 'none',
        'reports.groups': 'none',
        'files.upload': 'none',
        'files.download': 'none',
        'files.delete': 'none',
        'files.share': 'none'
      }
    },
    {
      id: 'admin_moduls',
      name: 'admin_moduls',
      description: 'Администратор образовательных модулей',
      permissions: {
        'system.manage': 'none',
        'system.backup': 'none',
        'system.logs.view': 'none',
        'system.config': 'none',
        'users.create': 'none',
        'users.edit': 'none',
        'users.delete': 'none',
        'users.view': 'none',
        'users.roles.assign': 'none',
        'groups.create': 'none',
        'groups.edit': 'none',
        'groups.delete': 'none',
        'groups.view': 'limited',
        'students.create': 'none',
        'students.edit': 'none',
        'students.delete': 'none',
        'students.assign_to_group': 'none',
        'course.create': 'full',
        'course.edit': 'full',
        'course.delete': 'full',
        'course.view': 'full',
        'course.assign_to_groups': 'full',
        'modules.create': 'full',
        'modules.edit': 'full',
        'modules.delete': 'full',
        'modules.view': 'full',
        'lab.create': 'limited',
        'lab.edit': 'limited',
        'lab.delete': 'none',
        'lab.view': 'full',
        'lab.execute': 'none',
        'lab.reset': 'none',
        'lab.assign_to_groups': 'full',
        'lab.template': 'limited',
        'container.create': 'none',
        'container.start': 'none',
        'container.stop': 'none',
        'container.delete': 'none',
        'container.console': 'none',
        'container.logs': 'none',
        'container.resources.manage': 'none',
        'grades.create': 'none',
        'grades.edit': 'none',
        'grades.view': 'limited',
        'grades.view_group': 'limited',
        'grades.export': 'limited',
        'results.download': 'limited',
        'audit.view': 'none',
        'audit.view_groups': 'none',
        'audit.export': 'none',
        'monitoring.view': 'none',
        'monitoring.resources': 'none',
        'reports.generate': 'full',
        'reports.groups': 'full',
        'files.upload': 'full',
        'files.download': 'full',
        'files.delete': 'limited',
        'files.share': 'full'
      }
    },
    {
      id: 'admin_audit',
      name: 'admin_audit',
      description: 'Администратор аудита и мониторинга',
      permissions: {
        'system.manage': 'none',
        'system.backup': 'none',
        'system.logs.view': 'full',
        'system.config': 'none',
        'users.create': 'none',
        'users.edit': 'none',
        'users.delete': 'none',
        'users.view': 'full',
        'users.roles.assign': 'none',
        'groups.create': 'none',
        'groups.edit': 'none',
        'groups.delete': 'none',
        'groups.view': 'none',
        'students.create': 'none',
        'students.edit': 'none',
        'students.delete': 'none',
        'students.assign_to_group': 'none',
        'course.create': 'none',
        'course.edit': 'none',
        'course.delete': 'none',
        'course.view': 'full',
        'course.assign_to_groups': 'none',
        'modules.create': 'none',
        'modules.edit': 'none',
        'modules.delete': 'none',
        'modules.view': 'full',
        'lab.create': 'none',
        'lab.edit': 'none',
        'lab.delete': 'none',
        'lab.view': 'full',
        'lab.execute': 'none',
        'lab.reset': 'none',
        'lab.assign_to_groups': 'none',
        'lab.template': 'none',
        'container.create': 'none',
        'container.start': 'none',
        'container.stop': 'none',
        'container.delete': 'none',
        'container.console': 'none',
        'container.logs': 'full',
        'container.resources.manage': 'none',
        'grades.create': 'none',
        'grades.edit': 'none',
        'grades.view': 'full',
        'grades.view_group': 'full',
        'grades.export': 'full',
        'results.download': 'full',
        'audit.view': 'full',
        'audit.view_groups': 'full',
        'audit.export': 'full',
        'monitoring.view': 'full',
        'monitoring.resources': 'full',
        'reports.generate': 'full',
        'reports.groups': 'full',
        'files.upload': 'none',
        'files.download': 'full',
        'files.delete': 'none',
        'files.share': 'none'
      }
    },
    {
      id: 'teacher',
      name: 'teacher',
      description: 'Преподаватель курса',
      permissions: {
        'system.manage': 'none',
        'system.backup': 'none',
        'system.logs.view': 'none',
        'system.config': 'none',
        'users.create': 'none',
        'users.edit': 'none',
        'users.delete': 'none',
        'users.view': 'none',
        'users.roles.assign': 'none',
        'groups.create': 'full',
        'groups.edit': 'full',
        'groups.delete': 'limited',
        'groups.view': 'full',
        'students.create': 'full',
        'students.edit': 'full',
        'students.delete': 'limited',
        'students.assign_to_group': 'full',
        'course.create': 'limited',
        'course.edit': 'full',
        'course.delete': 'limited',
        'course.view': 'full',
        'course.assign_to_groups': 'full',
        'modules.create': 'full',
        'modules.edit': 'full',
        'modules.delete': 'limited',
        'modules.view': 'full',
        'lab.create': 'full',
        'lab.edit': 'full',
        'lab.delete': 'full',
        'lab.view': 'full',
        'lab.execute': 'full',
        'lab.reset': 'limited',
        'lab.assign_to_groups': 'full',
        'lab.template': 'full',
        'container.create': 'limited',
        'container.start': 'full',
        'container.stop': 'full',
        'container.delete': 'full',
        'container.console': 'full',
        'container.logs': 'full',
        'container.resources.manage': 'limited',
        'grades.create': 'full',
        'grades.edit': 'full',
        'grades.view': 'full',
        'grades.view_group': 'full',
        'grades.export': 'full',
        'results.download': 'full',
        'audit.view': 'none',
        'audit.view_groups': 'limited',
        'audit.export': 'none',
        'monitoring.view': 'limited',
        'monitoring.resources': 'none',
        'reports.generate': 'full',
        'reports.groups': 'full',
        'files.upload': 'full',
        'files.download': 'full',
        'files.delete': 'full',
        'files.share': 'full'
      }
    },
    {
      id: 'student',
      name: 'student',
      description: 'Студент',
      permissions: {
        'system.manage': 'none',
        'system.backup': 'none',
        'system.logs.view': 'none',
        'system.config': 'none',
        'users.create': 'none',
        'users.edit': 'none',
        'users.delete': 'none',
        'users.view': 'none',
        'users.roles.assign': 'none',
        'groups.create': 'none',
        'groups.edit': 'none',
        'groups.delete': 'none',
        'groups.view': 'none',
        'students.create': 'none',
        'students.edit': 'none',
        'students.delete': 'none',
        'students.assign_to_group': 'none',
        'course.create': 'none',
        'course.edit': 'none',
        'course.delete': 'none',
        'course.view': 'full',
        'course.assign_to_groups': 'none',
        'modules.create': 'none',
        'modules.edit': 'none',
        'modules.delete': 'none',
        'modules.view': 'full',
        'lab.create': 'none',
        'lab.edit': 'none',
        'lab.delete': 'none',
        'lab.view': 'full',
        'lab.execute': 'full',
        'lab.reset': 'limited',
        'lab.assign_to_groups': 'none',
        'lab.template': 'none',
        'container.create': 'none',
        'container.start': 'full',
        'container.stop': 'full',
        'container.delete': 'none',
        'container.console': 'full',
        'container.logs': 'limited',
        'container.resources.manage': 'none',
        'grades.create': 'none',
        'grades.edit': 'none',
        'grades.view': 'limited',
        'grades.view_group': 'none',
        'grades.export': 'none',
        'results.download': 'full',
        'audit.view': 'none',
        'audit.view_groups': 'none',
        'audit.export': 'none',
        'monitoring.view': 'none',
        'monitoring.resources': 'none',
        'reports.generate': 'none',
        'reports.groups': 'none',
        'files.upload': 'full',
        'files.download': 'full',
        'files.delete': 'limited',
        'files.share': 'limited'
      }
    }
  ]

  return roles
})
